# Generated by Django 5.1 on 2024-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.DecimalField(decimal_places=2, max_digits=8)),
                ('p', models.DecimalField(decimal_places=2, max_digits=8)),
                ('k', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rainfall', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
